version: "3.7"

services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: calvin-evcc_server_1
      APP_PORT: 7070
      PROXY_AUTH_ADD: "false"

  server:
    image: docker.io/evcc/evcc:0.300.8
    init: true
    restart: on-failure
    ports:
      - 8887:8887/tcp
    volumes:
      - ${APP_DATA_DIR}/.evcc:/root/.evcc
      - ${APP_DATA_DIR}/evcc.yaml:/etc/evcc.yaml # optional
